[tool.pytest.ini_options]
minversion = "7.1.1"
addopts = "-ra"
testpaths = [
    "tests"
]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"

# log_file = "pytest.log"
# log_file_level = "DEBUG"
# log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
# log_file_date_format="%Y-%m-%d %H:%M:%S"
