FROM tensorflow/tensorflow:2.7.0-jupyter

RUN python -m pip install --upgrade pip \
    && python -m pip install scikit-learn==1.0.1 \
    tensorflow-hub==0.12.0 tensorflow-datasets==4.4.0 \
    seaborn==0.11.2
